package globals

const ERROR_CODE = "ERROR"
const ERROR_INVALID_PAYLOAD = "INVALID_PAYLOAD"
const ERROR_RESPONSE_JSON_CONVERSION = "RESPONSE_JSON_CONVERSION"
const ERROR_ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
const ERROR_EXISTENT_USER = "EXISTENT_USER"
const ERROR_DIFFERENT_PASSWORD = "DIFFERENT_PASSWORDS"
const ERROR_PASSWORD_MIN_LENGTH = "PASSWORD_MIN_LENGTH"
const ERROR_DATABASE_ERROR = "DATABASE_ERROR"
